### PR TITLE
Storybook integration

### LINKED ISSUE #4: Install Storybook
Let's install Storybook so we have a place to develop components in isolation. It's nice to develop components outside of the actual application so we know there aren't any hidden dependencies or coupling going on (we want to make sure components work alone, without needing other, arbitrary components).

https://storybook.js.org/

### PR DESCRIPTION
**Pull request by PatrickDev14**
Storybook ran migrations for missing-babelrc, React preset, and eslintPlugin

### CODE REVIEW

**Comment by kee-oth** [comment]
Let's finish this task and then update this PR to point to the new branch:

https://github.com/PatrickDev14/portfolio-v3/issues/8

**Comment by PatrickDev14** [comment]
I know that was a simple statement but I'll have to break it down. We're expanding my GitHub syntax with every step.
"finish this task" - does that mean merge the PR to the main branch?
"update this PR to point to the new branch" - I can search for an example, but do you mean the development branch?

**Comment by PatrickDev14** [comment]
`development` is now the base branch for this PR

**Comment by kee-oth** [comment]
> I know that was a simple statement but I'll have to break it down. We're expanding my GitHub syntax with every step.
> "finish this task" - does that mean merge the PR to the main branch?
> "update this PR to point to the new branch" - I can search for an example, but do you mean the development branch?

Sorry, I meant "let's finish the task linked below (issue #8)". And yeah! I meant the `development` branch 👍

**Comment by kee-oth** [comment]
@PatrickDev14 I had a bunch of errors caused by this page: `src/pages/mdx-page.mdx`

I had to delete it in order for Storybook to work correctly. Are you able to keep that page and also run Storybook successfully?

**Comment by PatrickDev14** [comment]
I tried a couple other approaches from the web, but ultimately `src/pages/mdx-page.mdx`  was also an issue for me locally. It was my mistake not to test it before you comment 5 days ago.
I'm merging this with the development branch.

**Pull request merged**
